# Generated by Django 6.0.7 on 2026-07-27 10:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="skills",
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("F", "Женский")],
                default="M",
                max_length=1,
                verbose_name="пол",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="employeeskilllevel",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills_levels",
                to="employees.employeeprofile",
            ),
        ),
        migrations.AlterField(
            model_name="employeeskilllevel",
            name="level",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="уровень",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="навык"),
        ),
    ]
