# Generated by Django 6.0.7 on 2026-07-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужской"), ("F", "Женский")], max_length=1
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("tester", "Тестировщик"),
                            ("backend", "Бэкенд‑разработчик"),
                            ("frontend", "Фронтенд‑разработчик"),
                            ("fullstack", "Fullstack"),
                            ("devops", "DevOps"),
                            ("manager", "Менеджер"),
                        ],
                        default="backend",
                        max_length=50,
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("desk_number", models.IntegerField(blank=True, null=True)),
                ("hire_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_photos/"
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Порядок фото в галерее"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="emp_app.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
    ]
