# Generated by Django 6.0.7 on 2026-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_images/"
            ),
        ),
        migrations.AlterField(
            model_name="employeeimage",
            name="order_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("F", "Женский")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="position",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="EmployeeSkill",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
